language: crystal

crystal:
  - latest
  - nightly

matrix:
  allow_failures:
    - crystal: nightly

install:
  - shards install

script:
  - crystal spec
  - crystal spec --no-debug
  - crystal spec --release
  - crystal spec --release --no-debug
  - crystal tool format --check
  - bin/ameba
